//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppergerWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class appergerEntities2 : DbContext
    {
        public appergerEntities2()
            : base("name=appergerEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Emocion> Emocion { get; set; }
        public virtual DbSet<Imagen> Imagen { get; set; }
        public virtual DbSet<ImagenTratamiento> ImagenTratamiento { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Selfie> Selfie { get; set; }
        public virtual DbSet<Tratamiento> Tratamiento { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<VideoTratamiento> VideoTratamiento { get; set; }
    }
}
