//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppergerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tratamiento()
        {
            this.Categoria = new HashSet<Categoria>();
            this.ImagenTratamiento = new HashSet<ImagenTratamiento>();
            this.Selfie = new HashSet<Selfie>();
            this.VideoTratamiento = new HashSet<VideoTratamiento>();
        }
    
        public int nIdTratamiento { get; set; }
        public Nullable<System.DateTime> dFechaInicio { get; set; }
        public Nullable<System.DateTime> dFechaFin { get; set; }
        public Nullable<bool> bSelfie { get; set; }
        public Nullable<bool> bImagen { get; set; }
        public Nullable<bool> bVideo { get; set; }
        public Nullable<int> nIdPsicologo { get; set; }
        public Nullable<int> nIdPaciente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categoria> Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenTratamiento> ImagenTratamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Selfie> Selfie { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoTratamiento> VideoTratamiento { get; set; }
    }
}
