//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiApperger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class appergerEntities : DbContext
    {
        public appergerEntities()
            : base("name=appergerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<Emocion> Emocion { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Selfie> Selfie { get; set; }
        public DbSet<Tratamiento> Tratamiento { get; set; }
        public DbSet<ImagenTratamiento> ImagenTratamiento { get; set; }
        public DbSet<VideoTratamiento> VideoTratamiento { get; set; }
        public DbSet<Imagen> Imagen { get; set; }
        public DbSet<Video> Video { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
