//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiApperger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Imagen = new HashSet<Imagen>();
            this.Video = new HashSet<Video>();
        }
    
        public int nIdCategoria { get; set; }
        public string sDescripcion { get; set; }
        public Nullable<int> nIdTratamiento { get; set; }
    
        public virtual Tratamiento Tratamiento { get; set; }
        public virtual ICollection<Imagen> Imagen { get; set; }
        public virtual ICollection<Video> Video { get; set; }
    }
}
