//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiApperger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen
    {
        public int nIdImagen { get; set; }
        public string sImagen { get; set; }
        public Nullable<int> nIdTratamiento { get; set; }
        public Nullable<int> nIdCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Tratamiento Tratamiento { get; set; }
    }
}
