//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiApperger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen
    {
        public Imagen()
        {
            this.ImagenTratamiento = new HashSet<ImagenTratamiento>();
        }
    
        public int nIdImagen { get; set; }
        public string sImagen { get; set; }
        public string sDescripcion { get; set; }
        public Nullable<int> nIdCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<ImagenTratamiento> ImagenTratamiento { get; set; }
    }
}
