//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiApperger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int nIdRol { get; set; }
        public string sDescripcion { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
