//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiApperger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selfie
    {
        public int nIdSelfie { get; set; }
        public Nullable<int> nIdTratamiento { get; set; }
        public Nullable<int> nIdEmocionElegida { get; set; }
        public Nullable<int> nIdEmocionRealizada { get; set; }
    
        public virtual Emocion Emocion { get; set; }
        public virtual Emocion Emocion1 { get; set; }
        public virtual Tratamiento Tratamiento { get; set; }
    }
}
