//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiApperger.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class usuario
    {
        public usuario()
        {
            this.Tratamiento = new HashSet<Tratamiento>();
            this.Tratamiento1 = new HashSet<Tratamiento>();
        }
    
        public int nIdUsuario { get; set; }
        public Nullable<int> nRol { get; set; }
        [DisplayName("Nombre")]
        public string sUsuario { get; set; }
        public string sApellido { get; set; }
        public Nullable<short> nEdad { get; set; }
        public Nullable<short> sMatricula { get; set; }
        public Nullable<System.DateTime> dFechaNacimiento { get; set; }
        public string sPais { get; set; }
        public string sProvincia { get; set; }
        public string sCiudad { get; set; }
        public Nullable<int> nPacienteDe { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual ICollection<Tratamiento> Tratamiento { get; set; }
        public virtual ICollection<Tratamiento> Tratamiento1 { get; set; }
    }
}
